stages:
  - build
  - test
  - deploy

build:maven:
  stage: build
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
      - grupo2-backend/target/
  script:
    - cd "grupo2-backend/"
    - mvn clean install
  artifacts:
    paths:
      - grupo2-backend/target/*.war

build:vite:
  stage: build
  image: node:16.5.0
  cache:
    key:
      files:
        - grupo2-frontend/package-lock.json
      prefix: npm
    paths:
      - grupo2-frontend/node_modules/
  script:
    - cd "grupo2-frontend/"
    - npm install
    - npm run build
  artifacts:
    paths:
      - grupo2-frontend/dist

test:maven:
  stage: test
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
    - grupo2-backend/target/
  script:
    - cd "grupo2-backend/"
    - mvn test

deploy:vite:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install openssh-client -y
    - sudo apt install zip -y && sudo apt install unzip -y
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY_FRONTEND" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - zip -r builded-frontend.zip grupo2-frontend/dist
    - ls a
    - cd grupo2-frontend/
    - ls a
    - cd dist/
    - ls a
  script:
    - scp -o StrictHostKeyChecking=no builded-frontend.zip ubuntu@13.233.134.103:/var/www/html
    - ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_IPADDRESS "sh ~/gitlab-prepare-prod-frontend.sh; sh ~/gitlab-deploy-prod-frontend.sh"

