image: maven:3.8.6-openjdk-18

stages:
  - build
  - test

cache:
  paths:
    - grupo2-backend/target/

build:
  stage: build
  script:
    - mvn clean install

test:
  stage: test
  script:
    - mvn test