stages:
  - build
  - test
  - deploy

build:maven:
  stage: build
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
      - grupo2-backend/target/
  script:
    - cd "grupo2-backend/"
    - mvn clean install
  artifacts:
    paths:
      - grupo2-backend/target/*.war

build:vite:
  stage: build
  image: node:16.5.0
  cache:
    key:
      files:
        - grupo2-frontend/package-lock.json
      prefix: npm
    paths:
      - grupo2-frontend/node_modules/
  script:
    - cd "grupo2-frontend/"
    - npm install
    - npm run build
  artifacts:
    paths:
      - grupo2-frontend/dist

test:maven:
  stage: test
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
    - grupo2-backend/target/
  script:
    - cd "grupo2-backend/"
    - mvn test

deploy:vite:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install openssh-client -y
    - apt-get install net-tools -y
    - apt-get install zip -y && apt-get install unzip -y
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY_FRONTEND" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - zip -r builded-frontend.zip grupo2-frontend/dist
    - ifconfig
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_IPADDRESS "sudo /etc/init.d/apache2 stop; sudo rm -r /tmp/frontend-backups/*; sudo mv /var/www/html/* /tmp/frontend-backups/"
    - scp -o StrictHostKeyChecking=no builded-frontend.zip ubuntu@$FRONTEND_IPADDRESS:/var/www/html
    - ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_IPADDRESS "sudo unzip /var/www/html/builded-frontend.zip; sudo mv grupo2-frontend/dist/* .; sudo rm -vr /var/www/html/builded-frontend.zip /var/www/html/grupo2-frontend; sudo /etc/init.d/apache2 start"

