stages:
  - build
  - test



build:maven:
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
      - grupo2-backend/target/
  script:
    - mvn clean install
  artifacts:
    paths:
      - grupo2-backend/target/*.war

test:maven:
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
    - grupo2-backend/target/
  script:
    - mvn test

build:vite:
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - grupo2-frontend/node_modules/
  script:
    - cd "grupo2-frontend"
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public

