stages:
  - build
  - test
  - deploy

build:maven:
  stage: build
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
      - grupo2-backend/target/
  script:
    - cd "grupo2-backend/"
    - mvn clean install
  artifacts:
    paths:
      - grupo2-backend/target/*.war

build:vite:
  stage: build
  image: node:16.5.0
  cache:
    key:
      files:
        - grupo2-frontend/package-lock.json
      prefix: npm
    paths:
      - grupo2-frontend/node_modules/
  script:
    - cd "grupo2-frontend/"
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - grupo2-frontend/public

test:maven:
  stage: test
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
    - grupo2-backend/target/
  script:
    - cd "grupo2-backend/"
    - mvn test

deploy:vite:
  stage: build
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install openssh-client -y
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY_FRONTEND" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_IPADDRESS "sh ~/gitlab-prepare-prod-frontend.sh; sh ~/gitlab-deploy-prod-frontend.sh"

