stages:
  - init
  - validate
  - plan
  - apply

image: registry.gitlab.com/gitlab-org/terraform-images/releases/1.3:v0.46.0

# Creating terraform remote state paths and endpoints
variables:
  TF_ROOT: ${CI_PROJECT_DIR}/Terraform
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/group2-infra

cache:
  key: group2-infra
  paths:
    - ${TF_ROOT}/.terraform

# Setting folders and credentials to use between terraform jobs
before_script:
  - mkdir ~/.aws/
  - mkdir ~/.google/
  - echo -e "$AWS_TERRAFORM_CREDENTIALS" > ~/.aws/credentials
  - cp $GOOGLE_TERRAFORM_CREDENTIALS ~/.google/credentials.json
  - cd ${TF_ROOT}

init:terraform:
  stage: init
  script:
    - gitlab-terraform init

validate:terraform:
  stage: validate
  script:
    - gitlab-terraform validate

plan:terraform:
  stage: plan
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:terraform:
  stage: apply
  environment:
    name: Terraform
  script:
    - gitlab-terraform apply
  dependencies:
    - plan:terraform
  when: manual
  only:
    - terraform-pipeline