stages:
  - build
  - test
  - deploy

# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

build:maven:
  stage: build
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
      - grupo2-backend/target/
  script:
    - cd "grupo2-backend/"
    - echo -e "$DOTENV_CONFIG_BACKEND" > src/main/resources/.env
    - mvn clean install
  artifacts:
    paths:
      - grupo2-backend/target/*.war

build:vite:
  stage: build
  image: node:16.5.0
  cache:
    key:
      files:
        - grupo2-frontend/package-lock.json
      prefix: npm
    paths:
      - grupo2-frontend/node_modules/
  script:
    - cd "grupo2-frontend/"
    - npm install
    - npm run build
  artifacts:
    paths:
      - grupo2-frontend/dist

test:maven:
  stage: test
  image: maven:3.8.6-openjdk-18
  cache:
    paths:
    - grupo2-backend/target/
  script:
    - cd "grupo2-backend/"
    - mvn test

deploy:maven:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install openssh-client -y
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY_BACKEND" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - mv grupo2-backend/target/*.war .
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$BACKEND_IPADDRESS "sudo /tmp/apache-tomcat-9.0.68/bin/shutdown.sh; sudo rm -r /tmp/backend-backups/*; sudo mv /tmp/apache-tomcat-9.0.68/webapps/* /tmp/backend-backups/; sudo mkdir /tmp/apache-tomcat-9.0.68/webapps/ROOT/"
    - scp -o StrictHostKeyChecking=no *.war ubuntu@$BACKEND_IPADDRESS:/tmp/apache-tomcat-9.0.68/webapps
    - ssh -o StrictHostKeyChecking=no ubuntu@$BACKEND_IPADDRESS "sudo /tmp/apache-tomcat-9.0.68/bin/startup.sh"

deploy:vite:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install openssh-client -y
    - apt-get install zip -y && apt-get install unzip -y
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY_FRONTEND" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - zip -r builded-frontend.zip grupo2-frontend/dist
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_IPADDRESS "sudo /etc/init.d/apache2 stop; sudo touch /var/www/html/hola.txt;sudo rm -r /tmp/frontend-backups/*; sudo mv /var/www/html/* /tmp/frontend-backups/"
    - scp -o StrictHostKeyChecking=no builded-frontend.zip ubuntu@$FRONTEND_IPADDRESS:/var/www/html
    - ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_IPADDRESS "cd /var/www/html/; sudo unzip builded-frontend.zip; sudo mv grupo2-frontend/dist/* .; sudo rm -vr builded-frontend.zip grupo2-frontend/; sudo /etc/init.d/apache2 start"
    - ssh -o StrictHostKeyChecking=no ubuntu@$FRONTEND_IPADDRESS "curl http://10.0.10.20:8080/v1/category; curl 10.0.10.20:8080/v1/category"
