FROM tomcat:9.0-jdk17-openjdk
ARG WAR_FILE=../grupo2-backend/target/*.war
RUN rm -rf /usr/local/tomcat/webapps/*
COPY ${WAR_FILE} /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
